modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"
issueTrackerURL="https://github.com/Lufurrius/mc-musketmod-reloaded/issues"

[[mods]]
modId="musketmod"
version="${mod_version}"
displayName="Musket Mod Reloaded"
#updateJSONURL=""
displayURL="https://github.com/Lufurrius/mc-musketmod-reloaded"
logoFile="logo.png"
credits="ewewukek, lilypuree, MikhailTapio, Xannosz, SkpC9 for their contribution"
authors="Lufurrius"
description='''
Small mod that adds craftable muskets and pistols.
'''

[[dependencies.musketmod]]
modId="neoforge"
type="required"
versionRange="[21.11.34-beta,)"
ordering="NONE"
side="BOTH"

[[dependencies.musketmod]]
modId="cloth_config"
type="required"
versionRange="[15.0,)"
ordering="NONE"
side="CLIENT"

[[mixins]]
config = "musketmod.mixins.json"
